---
- name: Playbook to install artemis
  hosts: all
  become: true

  vars_files:
    - secrets.yml
  
  roles:
  # Subscribe the newly provisioned servers and install pre-req packages
  - role: packages
  
  # Shared store role mounts an NFS share to use as a shared store
  - role: shared_store
    nfs_server: 192.168.0.4
    nfs_share: /vmware_templates/shared_store 
    shared_mount_dir: /var/lib/artemis-broker/sharedstore
    when: "'label_cluster_true' in groups"


  # This role is forked from https://github.com/remyma/ansible-artemis in galaxy
  - role: smapjb.ansible-artemis 
    artemis_version: "7.8.1"
    artemis_download_url: "http://toolchain.internal.croftvillas.com:8081/artifactory/ext-release-local/amq-broker-{{ artemis_version }}-bin.zip"
    artemis_journal_type: "ASYNCIO"
    artemis_web_host: "{{ ansible_fqdn }}"
    artemis_shared_store: "./sharedstore"
    jolokia_cors: 
      - "*://*"