---
- name: Playbook to install artemis
  hosts: all
  become: true

  vars_files:
    - secrets.yml

  roles:
    # Subscribe the newly provisioned servers and install pre-req packages
    - role: packages

    # This role is forked from https://github.com/remyma/ansible-artemis in galaxy
    - role: smapjb.ansible-artemis 
      artemis_version: "7.8.1"
      artemis_download_url: "http://gateway.internal.croftvillas.com/amq-broker-{{ artemis_version }}-bin.zip"
      artemis_journal_type: "ASYNCIO"
      artemis_web_host: "{{ ansible_fqdn }}"
      jolokia_cors: 
        - "*://*"