- name: Enable a Gluster repository
  rhsm_repository:
    name: "{{ 'rh-gluster-3-for-rhel-8-x86_64-rpms'  if ansible_facts.distribution_major_version  == '8' else 'rh-gluster-3-for-rhel-7-server-rpms' }}"
    state: enabled

- name: Make sure gluster is installed and started
  yum:
    name:
    - glusterfs-server
    state: latest

- name: Start up the gluster daemon
  service:
    name: glusterd
    state: started

- name: Ensure Gluster brick and mount directories exist.
  file: "path={{ item }} state=directory mode=0775"
  with_items:
    - "{{ gluster_brick_dir }}"
    - "{{ gluster_mount_dir }}"

- name: Configure Gluster volume.
  gluster_volume:
    state: present
    name: "{{ gluster_brick_name }}"
    brick: "{{ gluster_brick_dir }}"
    replicas: 2
    cluster: "{{ groups.label_cluster_true | join(',') }}"
    host: "{{ inventory_hostname }}"
    force: yes
  run_once: true

- name: Ensure Gluster volume is mounted.
  mount:
    name: "{{ gluster_mount_dir }}"
    src: "{{ inventory_hostname }}:/{{ gluster_brick_name }}"
    fstype: glusterfs
    opts: "defaults,_netdev"
    state: mounted